optimize:
  unsafeCache: true
  sourceMaps: false
#  sourceMaps: '#cheap-source-map'

code:
  redirectToNode: http://localhost:5601/{baseUrl}
  enableGlobalReference: false
#  repos:
#  - repo: 'github.com/Microsoft/TypeScript-Node-Starter'
#    init:
#      - 'yarn'
#      - 'install'